### ISSUE TITLE
Distinguish between different types of navigation (esp. for mobile)

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/n-navigation#92]
![image](https://cloud.githubusercontent.com/assets/224547/14560523/439bc3f6-0308-11e6-963c-de76be683368.png)

![image](https://cloud.githubusercontent.com/assets/224547/14560432/b9039dc2-0307-11e6-8817-4f2a203773e9.png)

1) All menu items have data-trackable of `header | primary-nav | group--more | secondary-navigation` but we need to detect whether clicks are of the left-hand "primary" type or the right-hand "sub-menu" type.

2) In the right-hand menu, distinguish between the "All [category]" type and the others.

**Comment by aintgoin2goa** [comment]
This module is responsible for the tracking, so closing.

Will create a new issue to deal with tracking in n-header-footer
